### ISSUE TITLE
Any fix to batched optimization?

### ISSUE THREAD

**Issue by TianningGao** [facebookresearch/bo_pr#3]
I noticed there's a "batch_size" parameter for experiments.run_one_replication(*) but in experiments_util.get_acqf(*), line 465 - 508, it will trigger some error on purpose if batch size is not 1. I tried to surpass the "batch_size == 1" condition but it triggers error elsewhere.

Is there any fix to enable batched optimization?

**Comment by Balandat** [comment]
I don't think we ran any batch sizes `q > 1` for the paper, so I'm not sure this is expected to work here - @sdaulton?

In general it's not hard to support this, but this is an archival repo, and so we wouldn't make the changes here (and instead in the BoTorch PR here: https://github.com/pytorch/botorch/pull/1533).

**Comment by TianningGao** [comment]
Got it. Thanks.
